# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_lmscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetails',
            name='startTime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='status',
            name='endTime',
            field=models.DateTimeField(default=None),
        ),
    ]
