# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20171206_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetails',
            name='startTime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='endTime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
